version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: finsight
      POSTGRES_USER: finsight
      POSTGRES_PASSWORD: finsight_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finsight
      SPRING_DATASOURCE_USERNAME: finsight
      SPRING_DATASOURCE_PASSWORD: finsight_pass
      JWT_SECRET: your_jwt_secret
      ALPHA_VANTAGE_API_KEY: your_alpha_vantage_key
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
